# Generated by Django 5.0.7 on 2024-07-10 18:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chore_tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choreassignment',
            name='date_assigned',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
